import {FaFootballBall, FaMusic, FaCoffee, FaLaptop,} from 'react-icons/fa'

export const Countries = [
    {
        label:'Arab',
        code:'ae'
    },
    {
        label:'Argentina',
        code:'ar'
    },
    {
        label:'Austria',
        code:'at'
    },
    {
        label:'Australia',
        code:'au'
    },
    {
        label:'Belgium',
        code:'be'
    },
    {
        label:'Bulgaria',
        code:'bg'
    },
    {
        label:'Brazil',
        code:'br'
    },
    {
        label:'Canada',
        code:'ca'
    },
    {
        label:'Switzerland',
        code:'ch'
    },
    {
        label:'China',
        code:'cn'
    },
    {
        label:'Colombia',
        code:'co'
    },
    {
        label:'Cuba',
        code:'cu'
    },
    {
        label:'Czechia',
        code:'cz'
    },
    {
        label:'Denmark',
        code:'de'
    },
    {
        label:'Egypt',
        code:'eg'
    },
    {
        label:'France',
        code:'fr'
    },
    {
        label:'United Kingdom',
        code:'gb'
    },
    {
        label:'Greece',
        code:'gr'
    },
    {
        label:'Hong Kong',
        code:'hk'
    },
    {
        label:'Hungary',
        code:'hu'
    },
    {
        label:'Indonesia',
        code:'id'
    },
    {
        label:'Ireland',
        code:'ie'
    },
    {
        label:'Israel',
        code:'il'
    },
    {
        label:'India',
        code:'in'
    },
    {
        label:'Italy',
        code:'it'
    },
    {
        label:'Japan',
        code:'jp'
    },
    {
        label:'Korea',
        code:'kr'
    },
    {
        label:'Lithuania',
        code:'lt'
    },
    {
        label:'Latvia',
        code:'lv'
    },
    {
        label:'',
        code:'ma'
    },
    {
        label:'Mexico',
        code:'mx'
    },
    {
        label:'Malaysia',
        code:'my'
    },
    {
        label:'Nigeria',
        code:'ng'
    },
    {
        label:'Netherlands',
        code:'nl'
    },
    {
        label:'Norway',
        code:'no'
    },
    {
        label:'New Zealand',
        code:'nz'
    },
    {
        label:'Philippines',
        code:'ph'
    },
    {
        label:'Poland',
        code:'pl'
    },
    {
        label:'Portugal',
        code:'pt'
    },
    {
        label:'Romania',
        code:'ro'
    },
    {
        label:'Serbia',
        code:'rs'
    },
    {
        label:'Russia',
        code:'ru'
    },
    {
        label:'Saudi Arabia',
        code:'sa'
    },
    {
        label:'Sweden',
        code:'se'
    },
    {
        label:'Singapore',
        code:'sg'
    },
    {
        label:'Slovenia',
        code:'si'
    },
    {
        label:'Slovakia',
        code:'sk'
    },
    {
        label:'Thailand',
        code:'th'
    },
    {
        label:'Turkey',
        code:'tr'
    },
    {
        label:'Taiwan',
        code:'tw'
    },
    {
        label:'Ukraine',
        code:'ua'
    },
    {
        label:'USA',
        code:'us'
    },
    {
        label:'Venezuela',
        code:'ve'
    },
    {
        label:'Algeria',
        code:'za'
    },
]

export const Categories = [
    {
        icon: <FaCoffee />,
        label:'Business',
        value:'business'
    },
    {
        icon: <FaMusic />,
        label:'Entertainment',
        value:'entertainment'
    },
    {
        label:'All News',
        value:'general'
    },
    {
        label:'Health',
        value:'health'
    },
    {
        label:'Science',
        value:'science'
    },
    {
        icon:<FaFootballBall />,
        label:'Sports',
        value:'sports'
    },
    {
        icon: <FaLaptop />,
        label:'Technology',
        value:'technology'
    },
]
